// Code generated by rlpgen. DO NOT EDIT.
//
// Manually extended for NIP-0004 Phase 10D — ResourceUsed and
// ResourceBasePrice cascade after ParentBeaconRoot. If this file is
// regenerated with rlpgen, re-apply the two _tmp flags + cascading writes
// at the end of the list, otherwise post-fork header RLP will diverge
// between nodes.

package types

import (
	"fmt"
	"io"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/rlp"
)

func (obj *Header) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	w.WriteBytes(obj.ParentHash[:])
	w.WriteBytes(obj.UncleHash[:])
	w.WriteBytes(obj.Coinbase[:])
	w.WriteBytes(obj.Root[:])
	w.WriteBytes(obj.TxHash[:])
	w.WriteBytes(obj.ReceiptHash[:])
	w.WriteBytes(obj.Bloom[:])
	if obj.Difficulty == nil {
		w.Write(rlp.EmptyString)
	} else {
		if obj.Difficulty.Sign() == -1 {
			return rlp.ErrNegativeBigInt
		}
		w.WriteBigInt(obj.Difficulty)
	}
	if obj.Number == nil {
		w.Write(rlp.EmptyString)
	} else {
		if obj.Number.Sign() == -1 {
			return rlp.ErrNegativeBigInt
		}
		w.WriteBigInt(obj.Number)
	}
	w.WriteUint64(obj.GasLimit)
	w.WriteUint64(obj.GasUsed)
	w.WriteUint64(obj.Time)
	w.WriteBytes(obj.Extra)
	w.WriteBytes(obj.MixDigest[:])
	w.WriteBytes(obj.Nonce[:])
	_tmp1 := obj.BaseFee != nil
	_tmp2 := obj.WithdrawalsHash != nil
	_tmp3 := obj.BlobGasUsed != nil
	_tmp4 := obj.ExcessBlobGas != nil
	_tmp5 := obj.ParentBeaconRoot != nil
	// NIP-0004 Phase 10D additions.
	_tmp6 := obj.ResourceUsed != nil
	_tmp7 := obj.ResourceBasePrice != nil
	if _tmp1 || _tmp2 || _tmp3 || _tmp4 || _tmp5 || _tmp6 || _tmp7 {
		if obj.BaseFee == nil {
			w.Write(rlp.EmptyString)
		} else {
			if obj.BaseFee.Sign() == -1 {
				return rlp.ErrNegativeBigInt
			}
			w.WriteBigInt(obj.BaseFee)
		}
	}
	if _tmp2 || _tmp3 || _tmp4 || _tmp5 || _tmp6 || _tmp7 {
		if obj.WithdrawalsHash == nil {
			w.Write([]byte{0x80})
		} else {
			w.WriteBytes(obj.WithdrawalsHash[:])
		}
	}
	if _tmp3 || _tmp4 || _tmp5 || _tmp6 || _tmp7 {
		if obj.BlobGasUsed == nil {
			w.Write([]byte{0x80})
		} else {
			w.WriteUint64((*obj.BlobGasUsed))
		}
	}
	if _tmp4 || _tmp5 || _tmp6 || _tmp7 {
		if obj.ExcessBlobGas == nil {
			w.Write([]byte{0x80})
		} else {
			w.WriteUint64((*obj.ExcessBlobGas))
		}
	}
	if _tmp5 || _tmp6 || _tmp7 {
		if obj.ParentBeaconRoot == nil {
			w.Write([]byte{0x80})
		} else {
			w.WriteBytes(obj.ParentBeaconRoot[:])
		}
	}
	// NIP-0004 Phase 10D — ResourceUsed.
	if _tmp6 || _tmp7 {
		if obj.ResourceUsed == nil {
			// Empty 5-tuple placeholder. ResourceLimits.EncodeRLP emits
			// the canonical zero list of five 0x80 bytes wrapped in a
			// list header; we mirror that exact byte sequence here so
			// downstream decoders pull back a zero ResourceLimits.
			w.Write([]byte{0xC5, 0x80, 0x80, 0x80, 0x80, 0x80})
		} else {
			if err := obj.ResourceUsed.EncodeRLP(w); err != nil {
				return err
			}
		}
	}
	if _tmp7 {
		if obj.ResourceBasePrice == nil {
			w.Write([]byte{0xC5, 0x80, 0x80, 0x80, 0x80, 0x80})
		} else {
			if err := obj.ResourceBasePrice.EncodeRLP(w); err != nil {
				return err
			}
		}
	}
	w.ListEnd(_tmp0)
	return w.Flush()
}

func (obj *Header) DecodeRLP(s *rlp.Stream) error {
	var fields []rlp.RawValue
	if err := s.Decode(&fields); err != nil {
		return err
	}
	if len(fields) < 15 {
		return fmt.Errorf("rlp: too few elements for types.Header, got %d", len(fields))
	}
	if len(fields) > 22 {
		return fmt.Errorf("rlp: too many elements for types.Header, got %d", len(fields))
	}
	obj.BaseFee = nil
	obj.WithdrawalsHash = nil
	obj.BlobGasUsed = nil
	obj.ExcessBlobGas = nil
	obj.ParentBeaconRoot = nil
	obj.ResourceUsed = nil
	obj.ResourceBasePrice = nil
	decode := func(index int, dst interface{}, name string) error {
		if err := rlp.DecodeBytes(fields[index], dst); err != nil {
			return fmt.Errorf("rlp: decode Header.%s: %w", name, err)
		}
		return nil
	}
	isEmptyString := func(index int, name string) (bool, error) {
		kind, content, _, err := rlp.Split(fields[index])
		if err != nil {
			return false, fmt.Errorf("rlp: decode Header.%s: %w", name, err)
		}
		return kind != rlp.List && len(content) == 0, nil
	}
	decodeOptionalHash := func(index int, dst **common.Hash, name string) error {
		empty, err := isEmptyString(index, name)
		if err != nil {
			return err
		}
		if empty {
			*dst = nil
			return nil
		}
		var value common.Hash
		if err := rlp.DecodeBytes(fields[index], &value); err != nil {
			return fmt.Errorf("rlp: decode Header.%s: %w", name, err)
		}
		*dst = &value
		return nil
	}
	decodeOptional := func(index int, dst interface{}, clear func(), name string) error {
		empty, err := isEmptyString(index, name)
		if err != nil {
			return err
		}
		if empty {
			clear()
			return nil
		}
		return decode(index, dst, name)
	}

	if err := decode(0, &obj.ParentHash, "ParentHash"); err != nil {
		return err
	}
	if err := decode(1, &obj.UncleHash, "UncleHash"); err != nil {
		return err
	}
	if err := decode(2, &obj.Coinbase, "Coinbase"); err != nil {
		return err
	}
	if err := decode(3, &obj.Root, "Root"); err != nil {
		return err
	}
	if err := decode(4, &obj.TxHash, "TxHash"); err != nil {
		return err
	}
	if err := decode(5, &obj.ReceiptHash, "ReceiptHash"); err != nil {
		return err
	}
	if err := decode(6, &obj.Bloom, "Bloom"); err != nil {
		return err
	}
	if err := decode(7, &obj.Difficulty, "Difficulty"); err != nil {
		return err
	}
	if err := decode(8, &obj.Number, "Number"); err != nil {
		return err
	}
	if err := decode(9, &obj.GasLimit, "GasLimit"); err != nil {
		return err
	}
	if err := decode(10, &obj.GasUsed, "GasUsed"); err != nil {
		return err
	}
	if err := decode(11, &obj.Time, "Time"); err != nil {
		return err
	}
	if err := decode(12, &obj.Extra, "Extra"); err != nil {
		return err
	}
	if err := decode(13, &obj.MixDigest, "MixDigest"); err != nil {
		return err
	}
	if err := decode(14, &obj.Nonce, "Nonce"); err != nil {
		return err
	}
	if len(fields) > 15 {
		if err := decodeOptional(15, &obj.BaseFee, func() { obj.BaseFee = nil }, "BaseFee"); err != nil {
			return err
		}
	}
	if len(fields) > 16 {
		if err := decodeOptionalHash(16, &obj.WithdrawalsHash, "WithdrawalsHash"); err != nil {
			return err
		}
	}
	if len(fields) > 17 {
		if err := decodeOptional(17, &obj.BlobGasUsed, func() { obj.BlobGasUsed = nil }, "BlobGasUsed"); err != nil {
			return err
		}
	}
	if len(fields) > 18 {
		if err := decodeOptional(18, &obj.ExcessBlobGas, func() { obj.ExcessBlobGas = nil }, "ExcessBlobGas"); err != nil {
			return err
		}
	}
	if len(fields) > 19 {
		if err := decodeOptionalHash(19, &obj.ParentBeaconRoot, "ParentBeaconRoot"); err != nil {
			return err
		}
	}
	if len(fields) > 20 {
		var value ResourceLimits
		if err := decode(20, &value, "ResourceUsed"); err != nil {
			return err
		}
		obj.ResourceUsed = &value
	}
	if len(fields) > 21 {
		var value ResourceLimits
		if err := decode(21, &value, "ResourceBasePrice"); err != nil {
			return err
		}
		obj.ResourceBasePrice = &value
	}
	return nil
}
