// Code generated by rlpgen. DO NOT EDIT.
//
// Manually extended for NIP-0004 Phase 10D — ResourceUsed and
// ResourceBasePrice cascade after ParentBeaconRoot. If this file is
// regenerated with rlpgen, re-apply the two _tmp flags + cascading writes
// at the end of the list, otherwise post-fork header RLP will diverge
// between nodes.

package types

import "github.com/ethereum/go-ethereum/rlp"
import "io"

func (obj *Header) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	w.WriteBytes(obj.ParentHash[:])
	w.WriteBytes(obj.UncleHash[:])
	w.WriteBytes(obj.Coinbase[:])
	w.WriteBytes(obj.Root[:])
	w.WriteBytes(obj.TxHash[:])
	w.WriteBytes(obj.ReceiptHash[:])
	w.WriteBytes(obj.Bloom[:])
	if obj.Difficulty == nil {
		w.Write(rlp.EmptyString)
	} else {
		if obj.Difficulty.Sign() == -1 {
			return rlp.ErrNegativeBigInt
		}
		w.WriteBigInt(obj.Difficulty)
	}
	if obj.Number == nil {
		w.Write(rlp.EmptyString)
	} else {
		if obj.Number.Sign() == -1 {
			return rlp.ErrNegativeBigInt
		}
		w.WriteBigInt(obj.Number)
	}
	w.WriteUint64(obj.GasLimit)
	w.WriteUint64(obj.GasUsed)
	w.WriteUint64(obj.Time)
	w.WriteBytes(obj.Extra)
	w.WriteBytes(obj.MixDigest[:])
	w.WriteBytes(obj.Nonce[:])
	_tmp1 := obj.BaseFee != nil
	_tmp2 := obj.WithdrawalsHash != nil
	_tmp3 := obj.BlobGasUsed != nil
	_tmp4 := obj.ExcessBlobGas != nil
	_tmp5 := obj.ParentBeaconRoot != nil
	// NIP-0004 Phase 10D additions.
	_tmp6 := obj.ResourceUsed != nil
	_tmp7 := obj.ResourceBasePrice != nil
	if _tmp1 || _tmp2 || _tmp3 || _tmp4 || _tmp5 || _tmp6 || _tmp7 {
		if obj.BaseFee == nil {
			w.Write(rlp.EmptyString)
		} else {
			if obj.BaseFee.Sign() == -1 {
				return rlp.ErrNegativeBigInt
			}
			w.WriteBigInt(obj.BaseFee)
		}
	}
	if _tmp2 || _tmp3 || _tmp4 || _tmp5 || _tmp6 || _tmp7 {
		if obj.WithdrawalsHash == nil {
			w.Write([]byte{0x80})
		} else {
			w.WriteBytes(obj.WithdrawalsHash[:])
		}
	}
	if _tmp3 || _tmp4 || _tmp5 || _tmp6 || _tmp7 {
		if obj.BlobGasUsed == nil {
			w.Write([]byte{0x80})
		} else {
			w.WriteUint64((*obj.BlobGasUsed))
		}
	}
	if _tmp4 || _tmp5 || _tmp6 || _tmp7 {
		if obj.ExcessBlobGas == nil {
			w.Write([]byte{0x80})
		} else {
			w.WriteUint64((*obj.ExcessBlobGas))
		}
	}
	if _tmp5 || _tmp6 || _tmp7 {
		if obj.ParentBeaconRoot == nil {
			w.Write([]byte{0x80})
		} else {
			w.WriteBytes(obj.ParentBeaconRoot[:])
		}
	}
	// NIP-0004 Phase 10D — ResourceUsed.
	if _tmp6 || _tmp7 {
		if obj.ResourceUsed == nil {
			// Empty 5-tuple placeholder. ResourceLimits.EncodeRLP emits
			// the canonical zero list of five 0x80 bytes wrapped in a
			// list header; we mirror that exact byte sequence here so
			// downstream decoders pull back a zero ResourceLimits.
			w.Write([]byte{0xC5, 0x80, 0x80, 0x80, 0x80, 0x80})
		} else {
			if err := obj.ResourceUsed.EncodeRLP(w); err != nil {
				return err
			}
		}
	}
	if _tmp7 {
		if obj.ResourceBasePrice == nil {
			w.Write([]byte{0xC5, 0x80, 0x80, 0x80, 0x80, 0x80})
		} else {
			if err := obj.ResourceBasePrice.EncodeRLP(w); err != nil {
				return err
			}
		}
	}
	w.ListEnd(_tmp0)
	return w.Flush()
}
