// Code generated by rlpgen. DO NOT EDIT.
// Ethernova: manually updated to include LastTouched field for state expiry.
// Backwards compatible: only encodes LastTouched when non-zero.
// This preserves genesis hash compatibility with pre-v1.0.4 chains.

package types

import (
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/rlp"
	"github.com/holiman/uint256"
	"io"
)

func (obj *StateAccount) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	w.WriteUint64(obj.Nonce)
	if obj.Balance == nil {
		w.Write(rlp.EmptyString)
	} else {
		w.WriteUint256(obj.Balance)
	}
	w.WriteBytes(obj.Root[:])
	w.WriteBytes(obj.CodeHash)
	// Ethernova: LastTouched encoding DISABLED in v1.0.7
	// Writing this field to the trie changes the state root and caused BAD BLOCK
	// errors between Windows and Linux nodes. The field exists in the struct but
	// is never persisted to the trie until we move it to a separate storage.
	// if obj.LastTouched > 0 {
	// 	w.WriteUint64(obj.LastTouched)
	// }
	w.ListEnd(_tmp0)
	return w.Flush()
}

func (obj *StateAccount) DecodeRLP(s *rlp.Stream) error {
	_, err := s.List()
	if err != nil {
		return err
	}

	// Field 1: Nonce
	if err := s.Decode(&obj.Nonce); err != nil {
		return err
	}

	// Field 2: Balance
	b := new(uint256.Int)
	if err := s.Decode(b); err != nil {
		return err
	}
	obj.Balance = b

	// Field 3: Root
	var root common.Hash
	if err := s.Decode(&root); err != nil {
		return err
	}
	obj.Root = root

	// Field 4: CodeHash
	if err := s.Decode(&obj.CodeHash); err != nil {
		return err
	}

	// Field 5: LastTouched (optional - backwards compatible with pre-v1.0.4)
	var lastTouched uint64
	if err := s.Decode(&lastTouched); err != nil {
		// Not present in old accounts - default to 0
		obj.LastTouched = 0
	} else {
		obj.LastTouched = lastTouched
	}

	return s.ListEnd()
}
